using ShenScope, Test
include("helpers.jl")
include("fixtures/compiler_ir.jl")
include("fixtures/semantic_transport.jl")
include("fixtures/compiler_archive.jl")
include("unit/compiler_ir.jl")
include("integration/compiler_ir_worker.jl")
include("unit/compiler_ir_protocol.jl")
include("unit/compiler_archive.jl")
include("integration/compiler_archive_cli.jl")
include("integration/backend_transport.jl")
include("unit/owned_operations.jl")
include("unit/compiler_source.jl")
include("unit/compiler_commit_receipts.jl")
include("integration/compiler_archive_agent.jl")
