using ShenScope, Test
include("helpers.jl")

include("unit/foundation.jl")
include("unit/durable_storage.jl")
include("unit/config.jl")
include("unit/memory.jl")
include("unit/extensions.jl")
include("unit/tasks.jl")
include("unit/protocol.jl")
include("unit/task_protocol.jl")
include("unit/tui.jl")
include("integration/providers.jl")
include("integration/agent_tools.jl")
include("integration/tasks.jl")
include("integration/cli.jl")
