using ShenScope, Test
include("helpers.jl")

include("unit/foundation.jl")
include("unit/durable_storage.jl")
include("unit/config.jl")
include("unit/memory.jl")
include("unit/extensions.jl")
include("unit/tasks.jl")
include("unit/protocol.jl")
include("unit/task_protocol.jl")
include("unit/mcp_schema.jl")
include("unit/mcp_protocol.jl")
include("unit/skills.jl")
include("unit/skills_protocol.jl")
include("unit/tui.jl")
include("integration/providers.jl")
include("integration/agent_tools.jl")
include("integration/tasks.jl")
include("integration/mcp_stdio.jl")
include("integration/mcp_http.jl")
include("integration/mcp_failures.jl")
include("integration/mcp_agent.jl")
include("integration/skills.jl")
include("integration/cli.jl")
